# Generated by copilot. Need to update, etc.
import pytest
import numpy as np
import healpy as hp
import os
from astropy.table import Table, hstack
from cosmotheka.mappers import MapperDESIBGS


NSIDE = 32  # Healpix nside for the tests
NPIX = hp.nside2npix(NSIDE)


@pytest.fixture
def config(
    catalog_path,
    catalog_pz_path,
    catalog_spec_path,
    stardens,
    ebv,
    randoms_path,
):
    return {
        "pzmin": 0.05,
        "pzmax": 0.25,
        "data_catalog": catalog_path,
        "data_catalog_pz": catalog_pz_path,
        "spec_catalog_xmatch": catalog_spec_path,
        "external_maps": [{'name': 'stardens',
                           'path': stardens,
                           'threshold': 2500},
                          {'name': 'ebv',
                           'path': ebv,
                           'threshold': 0.15}],
        "randoms_path": randoms_path,
        "randoms_selection": None,
        "nside": NSIDE,
        "coords": "C",
    }


@pytest.fixture
def rerun_config(config, tmp_path):
    config = config.copy()
    config["path_rerun"] = str(tmp_path)
    return config


@pytest.fixture(scope="module")
def stardens(tmp_path_factory):
    # Create a dummy stardens Table
    half_on = np.append(np.ones(int(NPIX / 2)), np.zeros(int(NPIX / 2)))
    stardens = half_on * 3000  # Second half will have stardens below 2500
    fn = tmp_path_factory.mktemp("data") / "stardens.fits"
    hp.write_map(fn, stardens, overwrite=True)
    return str(fn)


@pytest.fixture(scope="module")
def ebv(tmp_path_factory):
    # Create a dummy stardens Table
    half_on = np.append(np.ones(int(NPIX / 2)), np.zeros(int(NPIX / 2)))
    stardens = half_on * 0.2  # Second half will have ebv below 0.15
    fn = tmp_path_factory.mktemp("data") / "ebv.fits"
    hp.write_map(fn, stardens, overwrite=True)
    return str(fn)


@pytest.fixture(scope="module")
def catalog_path(tmp_path_factory):
    cat = get_catalog()
    fn = tmp_path_factory.mktemp("data") / "catalog.fits"
    cat.write(fn, overwrite=True)
    return str(fn)


@pytest.fixture(scope="module")
def catalog_pz_path(tmp_path_factory):
    cat = get_catalog_pz()
    fn = tmp_path_factory.mktemp("data") / "catalog_pz.fits"
    cat.write(fn, overwrite=True)
    return str(fn)


@pytest.fixture(scope="module")
def catalog_spec_path(tmp_path_factory):
    cat = get_catalog_spec()
    fn = tmp_path_factory.mktemp("data") / "catalog_spec.fits"
    cat.write(fn, overwrite=True)
    return str(fn)


@pytest.fixture
def catalog():
    return get_catalog()


@pytest.fixture
def catalog_pz():
    return get_catalog_pz()


@pytest.fixture
def catalog_spec():
    return get_catalog_spec()


@pytest.fixture(scope="module")
def randoms_path(tmp_path_factory):
    cat = get_catalog(randoms=True)
    basedir = tmp_path_factory.mktemp("randoms")
    fn10 = basedir / "randoms-1-0.fits"
    fn11 = basedir / "randoms-1-1.fits"
    cat.write(fn10, overwrite=True)
    cat.write(fn11, overwrite=True)
    return str(basedir)


def get_catalog(randoms=False):
    hnpix = NPIX // 2

    # Generate a catalog Table with columns
    ra, dec = hp.pix2ang(NSIDE, np.arange(NPIX), lonlat=True)
    on = np.ones(NPIX)
    zeros = np.zeros(NPIX)

    # Make first half fail but due to different cuts
    nobs_g = on * 2  # This will pass the threshold
    nobs_g[:5] = 1  # Make first five fail
    nobs_r = on * 2  # This will pass the threshold
    nobs_r[5:10] = 1  # Make first five fail
    nobs_z = on * 2  # This will pass the threshold
    nobs_z[5:10] = 1  # Make first five fail
    maskbits = zeros.copy().astype(int)
    maskbits[10:20] = 2048  # These will fail

    # Fluxes so that mag = 1
    flux = (5 / 10 ** (-2 / 5 + 9)) ** 2 * on

    # Half will pass the quality cuts and half the pzbin
    # Then, "remove_island" will remove more pixels
    cat = Table(
        {
            "TARGETID": np.arange(NPIX),
            "RA": ra,
            "DEC": dec,
            # Columns used for the quality cuts
            "NOBS_G": nobs_g,
            "NOBS_R": nobs_r,
            "NOBS_Z": nobs_z,
            "MASKBITS": maskbits,
            # Columns used for weights. With these values, the weights will be
            # w_North: 7, w_South: 14.
            "EBV": zeros,
            "GALDEPTH_G": flux,
            "GALDEPTH_R": flux,
            "GALDEPTH_Z": flux,
            "PSFSIZE_G": on,
            "PSFSIZE_R": on,
            "PSFSIZE_Z": on,
            "PHOTSYS": np.array(
                ["N", "S"] * hnpix
            ),  # Half will pass the masks
        }
    )
    # To test that these are removed when computing weights. These are the
    #  first 70 elements
    for i, key in enumerate(
        [
            "EBV",
            "GALDEPTH_G",
            "GALDEPTH_R",
            "GALDEPTH_Z",
            "PSFSIZE_G",
            "PSFSIZE_R",
            "PSFSIZE_Z",
        ]
    ):
        cat[key][i * 10 : (i + 1) * 10] = np.nan

    return cat


def get_catalog_pz():
    pz = np.random.uniform(0.1, 0.15, NPIX)
    cat = Table({"Z_PHOT_MEAN": pz,
                 "Z_PHOT_MEDIAN": pz,
                 "Z_PHOT_STD": 0.02*np.ones_like(pz)})
    return cat


def get_catalog_spec():
    # Generate a catalog Table with columns
    on = np.ones(NPIX)
    zeros = np.zeros(NPIX)

    cat = Table(
        {
            "TARGETID": np.arange(NPIX),
            "COADD_FIBERSTATUS": zeros,
            "ZWARN": zeros,
            "SPECTYPE": np.array(["GALAXY"] * NPIX),
            "Z": on * 0.12,
            "NPIXELS": on * 100,
        }
    )

    return cat


def get_mask_islands(cat):
    ra, dec = cat["RA"], cat["DEC"]

    toremove = (dec < -10.5) & (ra > 120) & (ra < 260)

    return toremove


@pytest.fixture()
def mapper(config):
    return MapperDESIBGS(config)


@pytest.fixture()
def mapper_with_islands(config_with_islands):
    return MapperDESIBGS(config_with_islands)


# Tests start here


def test_smoke(config):
    MapperDESIBGS(config)


def test_rerun(rerun_config):
    m = MapperDESIBGS(rerun_config)
    path_rerun = rerun_config["path_rerun"]

    # Noise
    mname = "DESI_BGS_zmin0.05_zmax0.25"
    nl = m.get_nl_coupled()
    fn = os.path.join(path_rerun,
                      f"{mname}_Nell_coordC_ns32.npz")
    d = np.load(fn)
    assert d["nls"].size == 32 * 3
    assert np.all(nl == d["nls"])

    # Clean randoms
    clean_randoms = m.get_clean_randoms_with_weights("randoms-1-0")
    fn = os.path.join(path_rerun, "randoms-1-0_clean_weights.fits.gz")
    read_randoms = Table.read(fn)
    assert len(clean_randoms) == len(read_randoms)

    # Randoms maps
    random_maps = m.get_randoms_maps()
    fn = os.path.join(
        path_rerun, f"map_{mname}_randoms-1-0_n-w-w2_coordC_ns32.fits.gz"
    )
    read_maps = hp.read_map(fn, field=None)

    fn = os.path.join(
        path_rerun, f"map_{mname}_randoms-1-1_n-w-w2_coordC_ns32.fits.gz"
    )
    read_maps += hp.read_map(fn, field=None)

    assert np.all(read_maps[0] == random_maps["n"])
    assert np.all(read_maps[1] == random_maps["w"])
    assert np.all(read_maps[2] == random_maps["w2"])


def test_get_default_cuts(mapper):
    cuts = mapper._get_default_cuts()
    assert isinstance(cuts, dict)
    assert cuts == {
        "min_nobs": 2,
        "target_maskbits": [1, 12, 13],
        "max_sigmaz": 0.05,
        "remove_island": True,
    }


@pytest.mark.parametrize(
    ("key", "val"),
    [
        ("target_maskbits", [1, 12, 14]),
        ("min_nobs", 3),
        ("max_sigmaz", 0.1),
        ("remove_island", False),
        ("mask_threshold", 0.3),
    ],
)
def test_suffix_generation(config, key, val):
    config[key] = val  # change from default
    mapper = MapperDESIBGS(config)
    if key != "mask_threshold":
        assert key.replace("_", "") in mapper.suffix_weights
    else:
        # mask_threshold is not used in suffix_weights
        assert key.replace("_", "") not in mapper.suffix_weights
    assert key.replace("_", "") in mapper.map_name


def test_suffix_generation_all_keys(config):
    # Set all keys to non-default values
    config["target_maskbits"] = [1, 12, 14]
    config["min_nobs"] = 3
    config["remove_island"] = False
    config["mask_threshold"] = 0.5  # Not used in suffix_weights
    config["max_sigmaz"] = 0.1

    mapper = MapperDESIBGS(config)
    suffix_weights = mapper.suffix_weights

    # Check that all keys are reflected in the suffix
    s = []
    for key in sorted(
        [
            "target_maskbits",
            "min_nobs",
            "remove_island",
            "max_sigmaz",
        ]
    ):
        s.append(key.replace("_", "") + str(config[key]))

    assert suffix_weights == "_".join(s)
    assert mapper.map_name.endswith(suffix_weights +
                                    "_maskthreshold0.5_zmin0.05_zmax0.25")


@pytest.mark.parametrize("syst", ['stardens', 'ebv'])
def test__get_external_mask(mapper, catalog, syst):
    # Also tested through quality cuts and get_catalog and randoms
    extmaps = mapper.config['external_maps']
    for maps in extmaps:
        if maps['name'] == 'stardens':
            fname = maps['path']
            threshold = maps['threshold']
    mask = mapper._get_map_threshold_mask(fname, threshold, catalog)
    assert np.sum(mask) == NPIX / 2
    assert np.all(mask[NPIX // 2 :])
    assert not np.any(mask[: NPIX // 2])


@pytest.mark.parametrize("randoms", [False, True])
def test__get_quality_cuts(config, randoms):
    # TODO: To test this properly, we might need to change a bit the catalog or
    # stardens
    catalog = hstack([get_catalog(randoms=randoms),
                      get_catalog_pz()])

    config2 = config.copy()
    config2["remove_island"] = False
    mapper = MapperDESIBGS(config2)

    mask = mapper._get_quality_cuts(catalog, randoms)
    assert np.sum(mask) == NPIX / 2
    assert np.all(mask[NPIX // 2 :])
    assert not np.any(mask[: NPIX // 2])

    mapper = MapperDESIBGS(config)
    mask_islands = get_mask_islands(catalog)
    mask_noisland = mapper._get_quality_cuts(catalog, randoms)

    assert np.all(mask * (~mask_islands) == mask_noisland)


def test_get_catalog(config):
    config2 = config.copy()
    # Don't remove islands for this test to make count easier
    config2["remove_island"] = False  # Default is True
    mapper = MapperDESIBGS(config2)
    cat = mapper.get_catalog()
    assert len(mapper.cat) == NPIX / 2

    mask = get_mask_islands(cat)
    cat = cat[~mask]  # Remove islands

    mapper = MapperDESIBGS(config)
    mapper.get_catalog()
    assert len(mapper.cat) == len(cat)


def test_get_nz(mapper):
    # This should be a delta function
    nz = mapper.get_nz()[1]
    assert len(np.unique(nz)) == 2
    # And the total should be the number of galaxies
    # in the catalog (which is the same as the
    # spectroscopic sample)
    cat = mapper.get_catalog()
    assert np.sum(nz) == len(cat)


def test_get_nl_coupled(mapper):
    # Rerun tested somewhere else
    nl = mapper.get_nl_coupled()
    assert np.all(nl == mapper._get_nl_coupled()["nls"])
