name: continuous-integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        py: [ 3.6 ]
        CC: [ gcc ]

    steps:
        - uses: actions/checkout@v2

        - name: Set up Python ${{ matrix.py }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.py }}

        - name: Install python dependencies
          run: |
            python -m pip install -U pip
            pip install -U numpy
            pip install -U scipy
            pip install -U flake8

        - name: Flake
          run: |
            flake8 xcell/mappers/

        - name: Cache pip
          uses: actions/cache@v2
          with:
            path: |
              ~/.cache/pip
            key: ${{ runner.os }}-${{ matrix.py }}-cache
            restore-keys: |
              ${{ runner.os }}-${{ matrix.py }}-cache
              ${{ runner.os }}-
