name: continuous-integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        py: [ 3.6 ]
        CC: [ gcc ]

    steps:
        - uses: actions/checkout@v2

        - name: Set up Python ${{ matrix.py }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.py }}
                    
        #- name: Cache pip
        #  uses: actions/cache@v2
        #  with:
        #    # Based on: https://medium.com/ai2-blog/python-caching-in-github-actions-e9452698e98d
        #    path: ${{ env.pythonLocation }}
        #    # Use hashFiles to regenerate cache when adding new dependencies
        #    key: ${{ env.pythonLocation }}-cache-${{ hashFiles('.github/workflows/pip-requirements.txt') }}

        - name: Install GSL, FFTW (linux)
          run: |
            sudo -H apt-get install libgsl-dev libfftw3-dev libcfitsio-dev

        - name: Install python dependencies
          run: |
            python -m pip install -U pip
            # TODO: Fix missing depenedencies with requirements
            # pip install -U -r .github/workflows/pip-requirements.txt
            pip install -U wheel
            pip install -U numpy
            pip install -U scipy
            pip install -U flake8
            pip install -U pytest
            pip install -U pytest-cov
            pip install -U astropy
            pip install -U healpy
            pip install -U pandas
            pip install -U pymaster
            pip install -U pyccl
            pip install -U camb
            pip install -U coveralls
            pip install -U sacc

        - name: Flake
          run: |
            flake8 xcell/

        - name: Python unit tests
          run: pytest -vv xcell --cov=xcell

        - name: coveralls
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run:
            coveralls --service=github
