name: continuous-integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        py: [ 3.10 ]
        CC: [ gcc ]

    steps:
        - uses: actions/checkout@v2

        - name: Set up mamba
          uses: conda-incubator/setup-miniconda@v2
          with:
            channels: conda-forge
            python-version: ${{ matrix.python-version }}
            show-channel-urls: true
            auto-update-conda: true
            use-mamba: true
            activate-environment: cosmotheka
            miniforge-version: latest

        - name: Install environment packages
          if: steps.cache.outputs.cache-hit != 'true'
          run: |
            export MAMBA_NO_BANNER=1
            mamba env update --file ${{ env.CONDA_ENV }}

        - name: Install TJPCov
          run: | 
            pip install . 

        - name: Python unit tests
          run: pytest -vv cosmotheka --cov=cosmotheka

        - name: Flake
          run: |
            flake8 cosmotheka/

        - name: coveralls
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run:
            coveralls --service=github
